# Generated by Django 5.1.7 on 2025-04-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(max_length=1000)),
                ('translated_text', models.TextField(max_length=1000)),
                ('response_text', models.TextField(max_length=1000)),
            ],
        ),
    ]
