# Generated by Django 5.1.7 on 2025-04-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bashin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchat',
            name='response_text_translation',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
