# Generated by Django 5.1.7 on 2025-04-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bashin', '0003_audiochat_textchat_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textchat',
            name='input_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='textchat',
            name='response_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='textchat',
            name='response_text_translation',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='textchat',
            name='translated_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
