# Generated by Django 5.1.7 on 2025-04-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bashin', '0004_alter_textchat_input_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiochat',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
