# Generated by Django 5.1.7 on 2025-04-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bashin', '0005_audiochat_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiochat',
            name='assistant_audio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='audiochat',
            name='user_audio',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
